version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /test/
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
